kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prom-k8s-rolebinding
  namespace: acm-monitoring
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prom-k8s-role
