kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prom-k8s-role
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - endpoints
